# Generated by Django 5.2.9 on 2026-01-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doner_name', models.CharField(max_length=200)),
                ('doner_email', models.EmailField(max_length=254)),
                ('doner_pho', models.CharField(max_length=10)),
                ('doner_pan', models.CharField(max_length=20)),
                ('doner_card', models.CharField(max_length=20)),
                ('doner_card_ex', models.CharField(max_length=10)),
                ('doner_cvv', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
