# Generated by Django 5.2.10 on 2026-02-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininfop',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='admininfop',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
