# Generated by Django 6.0.1 on 2026-01-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
