# Generated by Django 5.2.10 on 2026-02-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0002_alter_admininfop_mobile_alter_admininfop_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
