# Generated by Django 5.2.9 on 2026-01-28 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0002_doner_delete_donation_delete_event_delete_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='doner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doner',
            name='doner_cvv',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='doner',
            name='doner_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doner',
            name='doner_pan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doner',
            name='doner_pho',
            field=models.CharField(max_length=15),
        ),
    ]
