# Generated by Django 5.2.10 on 2026-02-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0003_alter_contactmessage_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
