# Generated by Django 5.2.9 on 2026-01-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0004_cause_donationsetting_donor_testimonial_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
