# Generated by Django 5.2.10 on 2026-02-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0005_alter_contactmessage_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininfop',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
