# Generated by Django 5.2.9 on 2026-01-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0005_alter_donor_transaction_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cause',
            options={},
        ),
        migrations.AlterModelOptions(
            name='donationsetting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
        migrations.RemoveField(
            model_name='cause',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='donationsetting',
            name='monthly_donors',
        ),
        migrations.RemoveField(
            model_name='donationsetting',
            name='states_covered',
        ),
        migrations.RemoveField(
            model_name='donationsetting',
            name='total_donors',
        ),
        migrations.RemoveField(
            model_name='donationsetting',
            name='total_raised',
        ),
        migrations.RemoveField(
            model_name='donationsetting',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='certificate_sent',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='pan_number',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='content',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='location',
        ),
        migrations.RemoveField(
            model_name='video',
            name='location',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='donationsetting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donationsetting',
            name='razorpay_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='donationsetting',
            name='razorpay_secret',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='cause',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cause',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cause',
            name='raised_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='donor',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
