# Generated by Django 5.2.10 on 2026-02-06 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0006_alter_admininfop_linkedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admininfo',
            name='direction_link',
        ),
        migrations.RemoveField(
            model_name='admininfo',
            name='map_embed_url',
        ),
        migrations.RemoveField(
            model_name='admininfo',
            name='photo',
        ),
    ]
