# Generated by Django 5.2.9 on 2026-01-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0007_donor_city_donor_is_verified_donor_pan_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationsetting',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
