# Generated by Django 5.2.9 on 2026-01-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0008_donationsetting_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DonationSetting',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.RenameField(
            model_name='cause',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='cause',
            old_name='raised_amount',
            new_name='collected_amount',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='created_at',
            new_name='donation_date',
        ),
        migrations.RemoveField(
            model_name='cause',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cause',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cause',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='cause',
            name='title',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='cause',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='name',
        ),
        migrations.AddField(
            model_name='cause',
            name='name',
            field=models.CharField(default='Default Cause', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='full_name',
            field=models.CharField(default='Anonymous Donor', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='tribute',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cause',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cause',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='donor',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online Payment'), ('bank', 'Bank Transfer'), ('upi', 'UPI Payment')], default='online', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donor',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
