# Generated by Django 6.0.1 on 2026-01-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0009_newslettersubscriber_delete_donationsetting_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cause',
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
    ]
