# Generated by Django 5.2.10 on 2026-02-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0011_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='cause',
        ),
        migrations.DeleteModel(
            name='Cause',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
