# Generated by Django 5.2.10 on 2026-02-02 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adpanel', '0013_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
