# Generated by Django 5.2.10 on 2026-02-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='created_at',
            new_name='date',
        ),
        migrations.AddField(
            model_name='donation',
            name='cardno',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='cvv',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='donation',
            name='expiry',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pan',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
