# Generated by Django 5.2.10 on 2026-02-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contactmessage_rename_created_at_donation_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
