# Generated by Django 6.0.1 on 2026-02-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='contact/hero/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20)),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(blank=True, max_length=254)),
                ('working_hours', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_embed_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='contact/team/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cause',
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
