# Generated by Django 5.2.10 on 2026-02-03 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='cause',
        ),
    ]
