# Generated by Django 5.2.10 on 2026-02-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_donation_cause_donation_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('subject', models.CharField(choices=[('donation', 'Donation Inquiry'), ('volunteer', 'Volunteer'), ('partnership', 'Partnership'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
