# Generated by Django 5.2.10 on 2026-02-17 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donation',
            new_name='Donations',
        ),
    ]
