# Generated by Django 5.2.10 on 2026-02-17 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_rename_donation_donations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donations',
            new_name='Donation',
        ),
    ]
