# Generated by Django 5.2.10 on 2026-02-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_rename_donations_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
