# Generated by Django 6.0.1 on 2026-01-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallerycustom_delete_galleryitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerycustom',
            name='is_active',
        ),
        migrations.AddField(
            model_name='gallerycustom',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
