# Generated by Django 6.0.1 on 2026-01-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_gallerycustom_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerycustom',
            name='created_at',
        ),
        migrations.AddField(
            model_name='gallerycustom',
            name='category',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='gallerycustom',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
