# Generated by Django 6.0.1 on 2026-01-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_donation_delete_gallerycustom'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
