# Generated by Django 5.2.10 on 2026-02-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_galleryitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='created_at',
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='slot',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
