# Generated by Django 6.0.1 on 2026-01-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_type',
            field=models.CharField(max_length=30),
        ),
    ]
