# Generated by Django 6.0.1 on 2026-01-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_alter_volunteer_volunteer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_type',
            field=models.CharField(max_length=50),
        ),
    ]
